### ISSUE TITLE
Почему "кодирование" попало в soft skills?

### ISSUE THREAD

**Issue by ardling** [productuniversity/softskills#2]
У вас есть целый блок про кодирование, но совершенно непонятно почему это попало в soft skills. На мой взгляд самый что ни на есть ХардЪ. Мой опыт говорит, что именно умение писать простой, понятный покрытый тестами и документацией код и есть сущность "знания языка X и платформы Y".

Можете пояснить почему вы включили кодирование в вашу выборку?

**Comment by amoreynis** [comment]
Возможно, этот блок стоит переназвать, чтобы было понятно "почему он попал в выборку".

Объясню логику. Просто программировать — большого ума не нужно :) Программишь и программишь. Но искусство состоит в том, чтобы не просто генерить строки код, а создавать код для продукта. Критерии хорошести такого кода — это понятность, простота внесения изменений и пр. И это отдельное искусство, коорое надо освоить. Оно не имеет отношения к умению программировать в общем.

**Comment by ardling** [comment]
Мне кажется вы излишне узко трактуете понятие программирования. В качестве свидетельства того, что умение программировать это не только знание алгоритмов и фреймворков я предлагаю вам хотя бы бегло ознакомиться с описанием 3х чрезвычайно популярных книг о программировании:
* "Чистый код" https://www.ozon.ru/context/detail/id/5011068/
* "Совершенный код" https://www.ozon.ru/context/detail/id/3159814/
* "Приемы объектно-ориентированного проектирования. Паттерны проектирования" https://www.ozon.ru/context/detail/id/2457392/

Все три книги написаны программистами для программистов, полны примеров кода и тем не менее все они про то, что нужно не "просто генерить строки кода", а искать простое и элегантное решение поставленной задачи которое будет легко понять и удобно развивать. Это не отдельное от программирования искусство, это и есть сама суть работы программиста как ее видят сами программисты. 

И это не софт-скилл хотя бы по той причине, что процесс овладевания этим искусством хард-скилловый - нужно писать программы, работать с кодом, читать документацию и книги по программированию. Можно сколько угодно ходить на митапы и общаться в кулуарах, но все познанное там будет благими пожеланиями пока не найдет свое воплощение в конкретном коде.

**Comment by amoreynis** [comment]
Не я трактую узко. К сожалению. Большинство так трактует. Очень хорошо, что для вас это естественно и входит в базовый уровнь хард скиллов. 

Для меня, например, искусство коммуникаций является хард скиллом по определению. Хотя для большинства других людей — нет.

Другими словами, разница между хард скиллами и софт скиллами, начиная с какого-то уровня, очень размыта. То есть, есть серая зона между абсолютно черным и абсолютно белым.

На мой взгляд, лишнее напоминание большинству о том, что это нужно — точно не помешает. думаю, что против такой постановки вы не имеете возражений. Что же касается тонкостей взглядов для определения того, как это назвать — бог с ним. Главное — чтобы было полезно.

**Comment by ardling** [comment]
Про большинство тоже вопрос весьма спорный. Для проверки я взял запрос в гугле "лучшие книги о программировании", первой выпавшей ссылкой было https://proglib.io/p/best-programming-books/ , там первые две книги из десяти это "Чистый код" и "Совершенный код". Думаю те кто внутри индустрии прекрасно понимают вещи о которых мы говорим.

Вы говорите о коммуникации как о хард скилле для себя. У меня немного другое разделение в голове. Софт - это то, чему можно научиться общаясь с другими людьми, скорее навык чем знание, а хард - знание, то чему можно научиться по книгам, курсам, в институте наконец. Почему это важно? Ппо той причине, что то, что у вас попало в кодирование отлично изучается по книгам и статьям. Как математика, пусть даже кому-то и нужен живой репетитор, она все равно остается хард-скилом. Этому не научишься только общаясь, нужно в какой-то момент сесть и начать решать уравнения. Опасно, если люди будут думать об этом как о софт-скиллах.

**Comment by amoreynis** [comment]
На мой взгляд — опасно, если они не будут думать об этом вообще.

В общем, позиции сформулированы и обозначены. Вашу я понял. Свою — тоже. Пока оставлю всё так, как есть.
